version: "3"

services:
  influx:
    image: influxdb:latest
    ports:
      - "8086:8086"
    volumes:
      - ./influx_data:/var/lib/influxdb/data
    environment:
      - INFLUXDB_DB=metrics
      - INFLUXDB_USER=user
      - INFLUXDB_USER_PASSWORD=userpassword
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=thiswouldbedifficulttoguess

  telegraf:
    image: telegraf:latest
    ports:
      - "8087:8087"
    expose:
      - "8087"
    depends_on:
      - influx
    volumes:
      - /proc:/host/proc:ro
      - ./telegraf_data/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    environment:
      - HOST_PROC=/host/proc

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    expose:
      - "3000"
    depends_on:
      - influx
    volumes:
      - ./grafana_data:/var/lib/grafana
